export * from './Primitives/HTag/Htag';
export * from './Primitives/Button/Button';
export * from './Primitives/P/P';
export * from './Primitives/Tag/Tag';
export * from './Primitives/Input/Input';
export * from './Primitives/Button/Button';
export * from './Primitives/Devider/Devider';
export * from './Primitives/Up/Up';

export * from './Raiting/Raiting';
export * from './Card/Card';
export * from './AdvantageBlock/AdvantageBlock';
export * from './HhData/HhData';
export * from './SeoBlock/SeoBlock';
export * from './Skills/Skills';
export * from './TextArea/TextArea';
export * from './Product/Product';
export * from './Review/Review';
export * from './ReviewForm/ReviewForm';
